config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"

  resources :articles

  get "signup", to: "users#new"
  resources :users, except: [:new]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 25}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }

  validates :username, presence: true, length: {minimum: 3, maximum: 25}, uniqueness: {case_sensitive: false}
  validates :email, presence: true, length: {maximum: 105}, uniqueness: {case_sensitive: false},
            format: {with: URI::MailTo::EMAIL_REGEXP}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:danger] = "You must be logged in to perform this action."
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :show, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.order(id: :desc).paginate(page: params[:page], per_page: 3)
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to article_path(@article)
    else
      render "new"
    end
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def show
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated."
      redirect_to article_path(@article)
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy

    flash[:notice] = "Article was successfully deleted."
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:error] = "You can only edit or delete your own articles."
      redirect_to articles_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.order(:name).paginate(page: params[:page], per_page: 25)
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = "Category has been created."
      redirect_to categories_path
    else
      render "new"
    end
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def show
    @category_articles = @category.articles.order(id: :desc).paginate(page: params[:page], per_page: 5)
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category has been updated."
      redirect_to category_path(@category.id)
    else
      render "edit"
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:error] = "Only admins can perform this action."
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in."
      redirect_to user_path(user.id)
    else
      flash.now[:error] = "Could not authenticate."
      render "new"
    end
  end

  def new
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have been logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 8)
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome to the Alpha Blog!"
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render "new"
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
    @articles = @user.articles.order(id: :desc).paginate(page: params[:page], per_page: 3)
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully."
      redirect_to articles_path
    else
      render "edit"
    end
  end

  def destroy
    if @user == current_user
      session[:user_id] = nil
    end

    @user.destroy
    flash[:danger] = "User and all user’s articles have been deleted."
    redirect_to users_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:error] = "You can only edit your own account."
      redirect_to users_path
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Only admin users can perform that action."
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "notice" then "alert alert-info"
    when "success" then "alert alert-success"
    when "error" then "alert alert-danger"
    when "alert" then "alert alert-warning"
    else
      "alert alert-primary"
    end
  end

  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"

    image_tag(gravatar_url, alt: user.username, class: "#{options[:class]}")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-sm-9">
      <h2><%= link_to article.title, article_path(article.id) %></h2>
    </div>
    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
      <div class="col-sm-3 mt-2 text-right">
        <%= link_to "edit", edit_article_path(article.id), class: "btn btn-sm btn-primary" %>
        <%= link_to "delete", article_path(article.id), method: :delete,
                    data: {confirm: "Are you sure?"},
                    class: "btn btn-sm btn-danger"%>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <p>
        <small>Written <%= time_ago_in_words(article.created_at) %> ago by <%= article.user.username %></small>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <%= simple_format(truncate(article.description, length: 100)) %>
    </div>
  </div>

  <% if article.categories.any? %>
    <div class="row">
      <div class="col-sm-12">
        <p>Filled under: <%= render article.categories %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article, title: "article" %>

<%= form_for @article do |f| %>
  <div class="form-group row">
    <%= f.label :title, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :description, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10 offset-sm-2">
      <%= f.collection_check_boxes :category_ids, Category.order(:name), :id, :name do |cb| %>
        <div class="form-check form-check-inline">
          <%= cb.label class: "form-check-input" do %>
            <%= cb.check_box class: "form-check-input" %> <%= cb.text %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10 offset-sm-2">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render "form" %>

<p><%= link_to "Back", url_for(:back) %></p>

app/views/articles/index.html.erb
<h1>All articles</h1>

<%= render "article", obj: @articles %>

<%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render "form" %>

<p><%= link_to "Back", url_for(:back) %></p>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>
  <small>Written <%= time_ago_in_words(@article.created_at) %> ago by <%= @article.user.username %></small>
</p>

<p><%= simple_format(@article.description) %></p>

<% if @article.categories.any? %>
  <hr>
  <p>
    Filled under: <%= render @article.categories %>
  </p>
<% end %>

<div>
  <hr>
  <%= link_to "View all articles", articles_path, class: "btn btn-sm btn-success" %>
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to "Edit article", edit_article_path(@article.id), class: "btn btn-sm btn-primary" %>
    <%= link_to "Delete article", article_path(@article.id), method: :delete,
                data: {confirm: "Are you sure you want to delete the article?"},
                class: "btn btn-sm btn-danger" %>
    <% end %>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-light">
  <%= link_to category.name, category_path(category.id) %>
</span>

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category, title: "category" %>

<%= form_for @category do |f| %>
  <div class="form-group row">
    <%= f.label :name, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10 offset-sm-2">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit a category</h1>

<%= render "form" %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<ul>
  <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, category_path(category.id) %>
      (<%= pluralize(category.articles.count, "article") %>)
    </li>
  <% end %>
</ul>

<%= will_paginate(@categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/categories/new.html.erb
<h1>Create a category</h1>

<%= render "form" %>

<p><%= link_to "Back", url_for(:back) %></p>

app/views/categories/show.html.erb
<div class="row">
  <div class="col-sm-9">
    <h1><%= @category.name %></h1>
  </div>
  <% if logged_in? && current_user.admin? %>
    <div class="col-sm-3 mt-2 text-right">
      <%= link_to "edit", edit_category_path(@category.id), class: "btn btn-sm btn-primary" %>
    </div>
  <% end %>
</div>

<%= render "articles/article", obj: @category_articles %>

<%= will_paginate(@category_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <div class="my-3">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= flash_class(key) %>" role="alert">
        <%= value %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="bg-light text-center">
    <span class="text-muted">&copy; 2018 Milan Vit</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Alpha blog", root_path, {class: "navbar-brand", id: "logo"} %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, {class: "nav-link"} %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, {class: "nav-link"} %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="categoryDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-label="categoryDropdown">
            <%= link_to "All Categories", categories_path, {class: "dropdown-item"} %>
            <div class="dropdown-divider"></div>

            <% Category.all.each do |category| %>
              <%= link_to category.name, category_path(category.id), {class: "dropdown-item"} %>
            <% end %>
          </div>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Actions
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "New Article", new_article_path, {class: "dropdown-item"} %>
              <%= link_to "New Category", new_category_path, {class: "dropdown-item"} if current_user.admin? %>
            </div>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "About", about_path, {class: "nav-link"} %>
        </li>
      </ul>

      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
              <span class="dropdown-item-text"><%= current_user.username %></span>
              <% if current_user.admin? %>
                <span class="dropdown-item-text">(Admin role)</span>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to "Edit profile", edit_user_path(current_user.id), {class: "dropdown-item"} %>
              <%= link_to "View profile", user_path(current_user.id), {class: "dropdown-item"} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, {class: "nav-link"} %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, {class: "nav-link"} %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Alpha blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
  <div class="container">
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>

    <main class="my-3">
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row my-2">
  <div class="col-sm">
    <h1>This is the About page…</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam maecenas ultricies mi eget. Faucibus ornare suspendisse sed nisi lacus sed viverra. Ut diam quam nulla porttitor massa id neque aliquam. Netus et malesuada fames ac turpis egestas sed tempus. Velit scelerisque in dictum non consectetur. Ultricies mi eget mauris pharetra et ultrices. Lectus urna duis convallis convallis tellus id interdum velit laoreet. Urna id volutpat lacus laoreet non curabitur gravida arcu. Nunc consequat interdum varius sit. Tellus integer feugiat scelerisque varius morbi enim. Diam sollicitudin tempor id eu nisl. Vitae purus faucibus ornare suspendisse. Dictum non consectetur a erat nam at lectus urna duis. Commodo nulla facilisi nullam vehicula ipsum. Quam viverra orci sagittis eu volutpat. Adipiscing elit ut aliquam purus. Semper auctor neque vitae tempus quam pellentesque nec. Blandit aliquam etiam erat velit scelerisque in dictum. Praesent semper feugiat nibh sed pulvinar.</p>
  </div>

  <div class="col-sm">
    <h1>… though there’s not much about it</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam maecenas ultricies mi eget. Faucibus ornare suspendisse sed nisi lacus sed viverra. Ut diam quam nulla porttitor massa id neque aliquam. Netus et malesuada fames ac turpis egestas sed tempus. Velit scelerisque in dictum non consectetur. Ultricies mi eget mauris pharetra et ultrices. Lectus urna duis convallis convallis tellus id interdum velit laoreet. Urna id volutpat lacus laoreet non curabitur gravida arcu. Nunc consequat interdum varius sit. Tellus integer feugiat scelerisque varius morbi enim. Diam sollicitudin tempor id eu nisl. Vitae purus faucibus ornare suspendisse. Dictum non consectetur a erat nam at lectus urna duis. Commodo nulla facilisi nullam vehicula ipsum. Quam viverra orci sagittis eu volutpat. Adipiscing elit ut aliquam purus. Semper auctor neque vitae tempus quam pellentesque nec. Blandit aliquam etiam erat velit scelerisque in dictum. Praesent semper feugiat nibh sed pulvinar.</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron text-center" id="welcome">
  <h1 class="display-4">ALPHA BLOG</h1>
  <%= link_to "Sign up now", signup_path, {class: "btn btn-primary btn-lg"} %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <h4 class="alert-heading">
      <%= pluralize(obj.errors.count, "error") %> prohibited this <%= title %> from being saved:
    </h4>

    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user, title: "user" %>

<%= form_for @user do |f| %>
  <div class="form-group row">
    <%= f.label :username, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :username, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :email, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.email_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :password, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10 offset-sm-2">
      <%= f.submit(@user.new_record? ? "Sign up" : "Update", class: "btn btn-primary") %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Update your account</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1>All bloggers</h1>

<div class="row">
  <% @users.each do |user| %>
    <div class="col-md-3 col-xs-12">
      <div class="card mb-3">
        <%= gravatar_for user, size: 300, class: "card-img-top" %>

        <div class="card-body">
          <h5 class="card-title"><%= user.username %></h5>
          <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
          <%= link_to "View profile", user_path(user.id), class: "btn btn-primary" %>
          <% if current_user.admin? %>
            <%= link_to "Delete", user_path(user.id), method: :delete,
                        data: {confirm: "Are you sure you want to delete this user and all of user’s articles?"},
                        class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1><%= @user.username %>’s profile</h1>

<div class="row">
  <div class="col-md-10">
    <h2>Articles</h2>

    <%= render "articles/article", obj: @articles %>
  </div>
  <div class="col-md-2">
    <div class="float-right">
      <%= gravatar_for @user, size: 150, class: "rounded-circle" %>
    </div>
  </div>
</div>

<%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>